# docker config for influx db + python
services:
  influxdb2:
    image: influxdb:2
    container_name: plender_influxdb2
    ports:
      - "8086:8086"
    volumes:
      - influxdb2_data:/var/lib/influxdb2
      - influxdb2_config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123!
      - DOCKER_INFLUXDB_INIT_ORG=nflx
      - DOCKER_INFLUXDB_INIT_BUCKET=default
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5
  sdetest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plender_sdetest
    volumes:
      - ./app:/usr/src/app
      - influxdb2_config:/usr/src/influxdb2_config
    working_dir: /usr/src/app
    depends_on:
      influxdb2:
        condition: service_healthy

volumes:
  influxdb2_data:
  influxdb2_config:
